{% set name = "bitshuffle" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kiyo-masui/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1bc30e79d6b0812fa82ea53089f20b38bd403bfd101a015f496fd94d06354838
  patches:
    - patch/0001-Do-not-override-conda-forge-compilation-flags.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.19
    - lz4
    - python
    - pip
    - numpy >=1.16
    - h5py
    - hdf5
  run:
    - python
    - numpy >=1.16
    - h5py
    - hdf5
    - cython

test:
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - test -f $PREFIX/lib/bitshuffle.a
    - find .
    - pytest --pyargs tests

about:
  home: https://github.com/kiyo-masui/bitshuffle
  summary: Filter for improving compression of typed binary data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Bitshuffle is an algorithm that rearranges typed, binary data for improving compression,
    as well as a python/C package that implements this algorithm within the Numpy framework.
  doc_url: https://github.com/kiyo-masui/bitshuffle
  dev_url: https://github.com/kiyo-masui/bitshuffle

extra:
  recipe-maintainers:
    - xmnlab
    - cpcloud
    - anthchirp
